### ISSUE TITLE
Webclient: Spielfunktionen

### ISSUE THREAD

**Issue by hche** [ViGor-Thinktank/GCML#5]
Login/Logout
Kampagne anlegen/verwalten
Spielfunktionen (plazieren, bewegen, Runde beenden)

**Comment by git-assi** [comment]
Thema Runde beenden/Tick

ICommand hat die Funktion "Register(void)" dh wenn ein User ein Command Objekt auswählt, muß die Controller nur "Register()" für dieses Command Objekt ausführen!

Tick führt dann alle ge"registerten" Commands aus

**Comment by git-assi** [comment]
Thema Command Handling ohne Command Object:

Ich habe bereits den Typ CommandInfo eingeführt (oder war Er das? egal!)  Unit beinhaltet "strAktCommandInfo" um u.A. vergleichen zu ob Command X = Command Y ([im Unit Context] eineindeutige String ID)

**Comment by hche** [comment]
strAktCommandInfo ist aber nur ein String mit den Sektoren - das CommandInfo-Objekt enthält alle Daten die der Client benötigt.

**Comment by git-assi** [comment]
Der string dient auch, wie geschrieben, nur zum Vergleichen/Darstellen in einfach lesbarer Form.
Wenn man dem User zB nur die CommandInfo Strings zuwirft der einen auswählt und zurückwirft kann man das CommandObjekt eindeutig bestimmen (aus neu erzeugten oder den gecachten)

ICommand.Register() legt dagegen einen Verweis auf das vollständige CommandObjekt in der Unit Instance ab

**Comment by hche** [comment]
Grundfunktionen sind implementiert - Benutzerverwaltung (Passwort anlegen/ändern) ist ein separater Punkt.
